networks:
  frontend:
  backend:

services:
  db:
    image: postgres:16
    restart: unless-stopped
    networks:
      - backend
      - frontend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      TZ: "America/Chicago"
      PGTZ: "America/Chicago"
    volumes:
      - postgres:/var/lib/postgresql/data
    secrets:
      - postgres-user
      - postgres-password
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: app/Dockerfile.dev
      secrets:
        - postgres-user
        - postgres-password
      args:
        POSTGRES_USER_FILE: /run/secrets/postgres-user
        POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    restart: unless-stopped
    networks:
      - frontend
      - backend
    ports:
      - "127.0.0.1:5173:5173"
      - "127.0.0.1:24678:24678"
      - "127.0.0.1:5555:5555"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
      - ./classes-prisma:/usr/src/classes-prisma
    environment:
      DEVELOPMENT: "true"
      TZ: "America/Chicago"
    depends_on:
      - db
    secrets:
      - postgres-user
      - postgres-password
  cron:
    env_file:
      - .env
    build:
      context: .
      dockerfile: cron-service/Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./cron-service:/var/task
      - /var/task/node_modules
      - ./classes-prisma:/classes-prisma
    networks:
      - backend

volumes:
  postgres:

secrets:
  postgres-user: 
    file: ./secrets/postgres-user.txt
  postgres-password: 
    file: ./secrets/postgres-password.txt

