# Base image
FROM node:lts

# Set environment variables
ENV NODE_ENV=development

# Set working directory
WORKDIR /usr/src/app

# Copy package.json from app subdirectory
COPY app/package*.json ./

# Install dependencies
RUN npm install

# Copy app source and shared schema
COPY app/ .
COPY classes-prisma/ /usr/src/classes-prisma/

# Expose ports for SvelteKit and Vite's HMR
EXPOSE 5173
EXPOSE 24678
EXPOSE 5555

COPY app/entrypoint.sh /entrypoint.sh
COPY app/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /entrypoint.sh \
    && chmod +x /wait-for-it.sh

ENTRYPOINT [ "/wait-for-it.sh", "db:5432", "-t", "10", "-s" , "--", "/entrypoint.sh" ]

# Start SvelteKit development server
CMD ["npm", "run", "deploy:dev"]
